---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: mujahidsoft/cfcli 
    tag: 0.1
inputs:
  - name: cfusagerepo
outputs:
  - name: email 
run:
  path: cfusagerepo/ci/scripts/usage-script.sh
